#pragma once
#include "BaseOps.h"
#include "AddOps.h"
#include "MatmulOps.h"
#include "MatmulFirstTOps.h"
#include "MatmulSecondOps.h"
#include "ElemulOps.h"
#include "FlattenOps.h"
#include "AddarrayOps.h"